[package]
name = "soter-boringssl"
version = "0.1.0"
edition = "2018"
authors = ["rust-themis developers"]

[dependencies]
soter-boringssl-sys = { path = "../soter-boringssl-sys", version = "=0.1.0" }
