name: Audit dependencies

on:
  schedule:
    - cron: '0 6 * * 6' # every Saturday at 6:00 UTC

jobs:
  audit:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v1
      # Preinstall a cached version to speed up the build
      - name: Install cargo-audit
        uses: actions-rs/install@v0.1
        # TODO(ilammy, 2020-08-08): enable this back once "actions-rs/install" is fixed
        # Currently it fails to install a newer version of cargo-audit because
        # the binary is already installed in the system.
        # https://github.com/actions-rs/install/issues/6
        if: ${{ false }}
        with:
          crate: cargo-audit
          use-tool-cache: true
      - name: Audit dependencies
        uses: actions-rs/audit-check@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
