name: Build checks

on:
  pull_request:
    branches:
    - master

jobs:
  test-macos:
    runs-on: macos-10.14
    steps:
    - name: Set up Rust toolchain
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
    - name: Check out code
      uses: actions/checkout@v1
      with:
        submodules: true
    - name: Run all tests
      run: cargo test

  test-ubuntu:
    runs-on: ubuntu-18.04
    steps:
    - name: Check out code
      uses: actions/checkout@v1
      with:
        submodules: true
    - name: Run all tests
      run: cargo test

  test-windows:
    runs-on: windows-2019
    steps:
    - name: 'Set up BoringSSL dependencies: Ninja'
      uses: seanmiddleditch/gha-setup-ninja@master
      with:
        destination: ../ninja-build
    - name: 'Set up BoringSSL dependencies: NASM'
      uses: ilammy/setup-nasm@v1
    - name: Set up Microsoft Visual C++ environment
      uses: ilammy/msvc-dev-cmd@v1
    - name: Check out code
      uses: actions/checkout@v1
      with:
        submodules: true
    - name: Run all tests
      run: cargo test
