name: Build checks

on:
  pull_request:
    branches:
    - master

jobs:
  test:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v1
      with:
        submodules: true
    - name: Run tests
      run: cargo test
